import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders


def send_email(destination, attachments):

    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")
    smtp_server = os.getenv("SMTP_SERVER")
    smtp_port = os.getenv("SMTP_PORT")

    message = MIMEMultipart()
    message["From"] = smtp_user
    message["To"] = destination
    message["Subject"] = "Automated Sales Report"

    body = "Automated report generated by the data pipeline."
    message.attach(MIMEText(body, "plain"))

    for file in attachments:

        with open(file, "rb") as attachment:

            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())

        encoders.encode_base64(part)

        part.add_header(
            "Content-Disposition",
            f"attachment; filename={file}",
        )

        message.attach(part)

    server = smtplib.SMTP(smtp_server, int(smtp_port))
    server.starttls()
    server.login(smtp_user, smtp_password)

    server.send_message(message)
    server.quit()
